export const GET_MOVIE = "CINEMAPAGE/GET_MOVIE"
export const GET_MOVIE_SUCCESS = "CINEMAPAGE/GET_MOVIE_SUCCESS"
export const GET_MOVIE_FAIL = "CINEMAPAGE/GET_MOVIE_FAIL"

export const GET_CINEMA = "CINEMAPAGE/GET_CINEMA"
export const GET_CINEMA_SUCCESS = "CINEMAPAGE/GET_CINEMA_SUCCESS"
export const GET_CINEMA_FAIL = "CINEMAPAGE/GET_CINEMA_FAIL"

export const GET_SHOWTIMES = "CINEMAPAGE/GET_SHOWTIMES"
export const GET_SHOWTIMES_SUCCESS = "CINEMAPAGE/GET_SHOWTIMES_SUCCESS"
export const GET_SHOWTIMES_FAIL = "CINEMAPAGE/GET_SHOWTIMES_FAIL"