export const GET_MOVIE = "BUYTICKETPAGE/GET_MOVIE"
export const GET_MOVIE_SUCCESS = "BUYTICKETPAGE/GET_MOVIE_SUCCESS"
export const GET_MOVIE_FAIL = "BUYTICKETPAGE/GET_MOVIE_FAIL"

export const GET_CINEMA = "BUYTICKETPAGE/GET_CINEMA"
export const GET_CINEMA_SUCCESS = "BUYTICKETPAGE/GET_CINEMA_SUCCESS"
export const GET_CINEMA_FAIL = "BUYTICKETPAGE/GET_CINEMA_FAIL"

export const GET_SHOWTIMES = "BUYTICKETPAGE/GET_SHOWTIMES"
export const GET_SHOWTIMES_SUCCESS = "BUYTICKETPAGE/GET_SHOWTIMES_SUCCESS"
export const GET_SHOWTIMES_FAIL = "BUYTICKETPAGE/GET_SHOWTIMES_FAIL"