export const GET_MOVIE = "MOVIEDETAILPAGE/GET_MOVIE"
export const GET_MOVIE_SUCCESS = "MOVIEDETAILPAGE/GET_MOVIE_SUCCESS"
export const GET_MOVIE_FAIL = "MOVIEDETAILPAGE/GET_MOVIE_FAIL"

export const GET_MOVIES = "MOVIEDETAILPAGE/GET_MOVIES"
export const GET_MOVIES_SUCCESS = "MOVIEDETAILPAGE/GET_MOVIES_SUCCESS"
export const GET_MOVIES_FAIL = "MOVIEDETAILPAGE/GET_MOVIES_FAIL"

export const GET_CINEMA = "MOVIEDETAILPAGE/GET_CINEMA"
export const GET_CINEMA_SUCCESS = "MOVIEDETAILPAGE/GET_CINEMA_SUCCESS"
export const GET_CINEMA_FAIL = "MOVIEDETAILPAGE/GET_CINEMA_FAIL"

export const GET_SHOWTIMES = "MOVIEDETAILPAGE/GET_SHOWTIMES"
export const GET_SHOWTIMES_SUCCESS = "MOVIEDETAILPAGE/GET_SHOWTIMES_SUCCESS"
export const GET_SHOWTIMES_FAIL = "MOVIEDETAILPAGE/GET_SHOWTIMES_FAIL"