export const LOGIN = "WRAPPEDMENU/LOGIN"
export const LOGINSUCCESS = "WRAPPEDMENU/LOGINSUCCESS"
export const LOGINFAIL = "WRAPPEDMENU/LOGINFAIL"

export const REGISTER = "WRAPPEDMENU/REGISTER"
export const REGISTERSUCCESS = "WRAPPEDMENU/REGISTERSUCCESS"
export const REGISTERFAIL = "WRAPPEDMENU/REGISTERFAIL"


export const HANDLEDIALOG = "WRAPPEDMENU/HANDLEDIALOG"
export const HANDLELOGOUT = "WRAPPEDMENU/HANDLELOGOUT"
export const HANDLECHANGETEXT = "WRAPPEDMENU/HANDLECHANGETEXT"
export const HANDLECHANGEDATE= "WRAPPEDMENU/HANDLECHANGEDATE"
export const HANDLECHANGETYPEFORM= "WRAPPEDMENU/HANDLECHANGETYPEFORM"