export const GET_TICKETS = "CINEMAPAGE/GET_TICKETS"
export const GET_TICKETS_SUCCESS = "CINEMAPAGE/GET_TICKETS_SUCCESS"
export const GET_TICKETS_FAIL = "CINEMAPAGE/GET_TICKETS_FAIL"

export const SAVE_INFO = "CINEMAPAGE/SAVE_INFO"
export const SAVE_INFO_SUCCESS = "CINEMAPAGE/SAVE_INFO_SUCCESS"
export const SAVE_INFO_FAIL = "CINEMAPAGE/SAVE_INFO_FAIL"

export const GET_SHOWTIMES = "CINEMAPAGE/GET_SHOWTIMES"
export const GET_SHOWTIMES_SUCCESS = "CINEMAPAGE/GET_SHOWTIMES_SUCCESS"
export const GET_SHOWTIMES_FAIL = "CINEMAPAGE/GET_SHOWTIMES_FAIL"

export const HANDLECHANGETEXT = "CINEMAPAGE/HANDLECHANGETEXT"
export const HANDLECHANGEDATE= "CINEMAPAGE/HANDLECHANGEDATE"
export const HANDLE_INIT_DATA= "CINEMAPAGE/HANDLE_INIT_DATA"
export const HANDLE_INIT_DATA_SUCCESS = "CINEMAPAGE/HANDLE_INIT_DATA_SUCCESS"
export const HANDLE_INIT_DATA_FAIL = "CINEMAPAGE/HANDLE_INIT_DATA_FAIL"
export const HANDLEDIALOG = "CINEMAPAGE/HANDLEDIALOG"